AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  credentials

  module for credentials handling and scope limitation for strava-aws-serverless project

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst


Resources:
  KmsKeyUserRole:
    Type: AWS::IAM::Role
    Properties: 
      Description: String
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Tags: 
        - Key: project
          Value: strava-aws-serverless
        - Key: module
          Value: credentials

Outputs:
  KmsKeyUserRole: 
    Value: !Ref KmsKeyUserRole
    Description: Role used for KMS utilization with lambda